theme = "rose_pine"

[editor]
true-color = true
auto-completion = true
auto-format = true
idle-timeout = 0
jump-label-alphabet = "asdfjklghzxcvbnmqwertyuiop"

[editor.indent-guides]
render = false
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-h = "jump_view_left"
C-l = "jump_view_right"
C-j = "jump_view_down"
C-k = "jump_view_up"

# Some nice Helix stuff
"C-." = "expand_selection"
"C-," = "shrink_selection"
C-n = "goto_next_change"
C-p = "goto_prev_change"
C-f = "select_next_sibling"
C-b = "select_prev_sibling"
"'" = "goto_word"
"*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
]

"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
V = ["select_mode", "extend_to_line_bounds"]

[editor.file-picker]
hidden = false
