[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--config", ".prettierrc", "--parser", "html"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--config", ".prettierrc", "--parser", "json"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--config", ".prettierrc", "--parser", "css"] }
auto-format = true

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--config", ".prettierrc", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--config", ".prettierrc", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--config", ".prettierrc", "--parser", "typescript"] }
auto-format = true