
## typescript
[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
config.hostInfo = "helix"

## golang
[language-server.gopls]
command = "gopls"

[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--out-format", "json", "--issues-exit-code=1"]


## prettier
[language-server.efm-lsp-prettier]
command = "efm-langserver"

[language-server.efm-lsp-prettier.config]
documentFormatting = true

[[language-server.efm-lsp-prettier.config.languages.javascript]]
formatCommand ="prettierd --stdin-filepath ${INPUT}"
formatStdin = true


[[language]]
name = "typescript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  { name = "tailwindcss-react" },
  { name = "efm-lsp-prettier", only-features = [ "format" ] },
]

[[language]]
name = "tsx"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  { name = "tailwindcss-react" },
  { name = "efm-lsp-prettier", only-features = [ "format" ] },
]

[[language]]
name = "jsx"
grammar = "javascript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  { name = "tailwindcss-react" },
  { name = "efm-lsp-prettier", only-features = [ "format" ] },
]

[[language]]
name = "javascript"
auto-format = true
language-servers = [
  { name = "typescript-language-server", except-features = [ "format" ] },
  { name = "tailwindcss-react" },
  { name = "efm-lsp-prettier", only-features = [ "format" ] },
]

[[language]]
name = "html"
auto-format = true
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] } ]

[[language]]
name = "json"
auto-format = true
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] } ]

[[language]]
name = "css"
auto-format = true
language-servers = [ { name = "efm-lsp-prettier", only-features = [ "format" ] } ]

