[language-server.efm]
command = "efm-langserver"

[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]
config.hostInfo = "helix"

[language-server.gopls]
command = "gopls"

[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--out-format", "json", "--issues-exit-code=1"]

[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { userLanguages = { tsx = "html", "*.tsx" = "html" } }

[[language]]
name = "typescript"
language-servers = [
  { name = "tailwindcss-ls"},
  { name = "typescript-language-server", except-features = [ "format" ] },
]
formatter = { command = 'prettier', args = ["--config", ".prettierrc", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  { name = "tailwindcss-ls"},
  { name = "typescript-language-server", except-features = [ "format" ] }
]
formatter = { command = 'prettier', args = ["--config", ".prettierrc", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [
  { name = "tailwindcss-ls"},
  { name = "typescript-language-server", except-features = [ "format" ] }
]
grammar = "javascript"
formatter = { command = 'prettier', args = ["--config", ".prettierrc", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  { name = "tailwindcss-ls"},
  { name = "typescript-language-server", except-features = [ "format" ] },
]
formatter = { command = 'prettier', args = ["--config", ".prettierrc", "--parser", "typescript"] }
indent = { tab-width = 4, unit = "\t" }
auto-format = true

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--config", ".prettierrc", "--parser", "html"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--config", ".prettierrc", "--parser", "json"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--config", ".prettierrc", "--parser", "css"] }
auto-format = true

